version: '3'
services:
  web:
    build: .
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
     - .:/home/dem/solution/Documents/docker
    image: petfinderimage
    ports:
      [8000:8000]
    environment:
      - DATABASE_URL="postgresql://demilew:Demian752728@localhost/pet_db"
  
    depends_on:
    - db
   
  
  db:
    image: postgres:15-alpine
    restart: always


    expose:
      - 5432
      
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demilew
      - POSTGRES_PASSWORD=Demian752728
      - POSTGRES_DB=pet_db


volumes:
  postgres_data_prod:      
