version: '3'

services:
  fast_api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
     - .:/app
    # container_name: "PetFinderFastAPI"
    image: pet_finder_api_container
    ports:
      [8008:8000]
    environment:
      - DATABASE_URL="postgresql://demilew:Demian752728@localhost/pet_db"
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=demilew
      - POSTGRES_PASSWORD=Demian752728
      - POSTGRES_DB=pet_db


volumes:
  postgres_data_prod:      
